#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	local enabled

	config_load service_ap
	config_get_bool enabled main enabled 1
	[ "$enabled" = 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/service_ap.sh
	procd_set_param respawn 3600 5 0
	procd_close_instance
}
